name: CI

on:
  push:
    branches: [ experiment-decoupling ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SUBSTITUTIONS: "
            _PROJECT=gcp-ml-172005,\
            _REGION=us-central1,\
            _REPO_URL=https://github.com/deep-diver/Model-Training-as-a-CI-CD-System,\
            _BRANCH=experiment-decoupling,\
            _PIPELINE_NAME=tfx-pipeline,\
            "    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.RUN_SA_EMAIL }}
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      - name: check if something changed
        uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          base: 'experiment-decoupling'        
          filters: |
            pipeline:
              - 'tfx-pipeline/**'
            modules:
              - 'modules/**'

      - name: trigger cloud build based on pipeline changes
        if: ${{ steps.filter.outputs.pipeline == 'true' }}
        run: |
          gcloud builds submit --no-source --timeout=60m \
          --config build/full-pipeline-deployment.yaml \
          --substitutions $SUBSTITUTIONS \
          --machine-type=n1-highcpu-8

      - name: trigger cloud build based on modules changes
        if: ${{ steps.filter.outputs.modules == 'true' }}
        run: |
          gcloud builds submit --no-source --timeout=60m \
          --config build/partial-pipeline-deployment.yaml \
          --substitutions $SUBSTITUTIONS \
          --machine-type=n1-highcpu-8
