name: CI

on:
#   push:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.RUN_SA_EMAIL }}
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}

      # - name: check if components folder has anything changed
      #   uses: dorny/paths-filter@v2
      #   id: my-pipeline-change
      #   with:
      #       filters: |
      #           src:
      #             - 'example/my-pipeline/**'

      - name: trigger cloud build based on component changes
        # if: steps.my-pipeline-change.outputs.components == 'true'
        run: |
          gcloud builds submit --no-source --timeout=60m \
          --config build/pipeline-deployment.yaml \
          --substitutions \
            _PROJECT=gcp-ml-172005,\
            _REGION=us-central1,\
            _REPO_URL=https://github.com/deep-diver/Model-Training-as-a-CI-CD-System,\
            _BRANCH=main,\
            _PIPELINE_NAME=my-pipeline \
          --machine-type=n1-highcpu-8
